d={}
name=input("Enter the name as the key value: ")
lang=input("Enter the language as the value: ")
d.update({name:lang})
name=input("Enter the name as the key value: ")
lang=input("Enter the language as the value: ")
d.update({name:lang})
name=input("Enter the name as the key value: ")
lang=input("Enter the language as the value: ")
d.update({name:lang})
name=input("Enter the name as the key value: ")
lang=input("Enter the language as the value: ")
d.update({name:lang})
print(d)
